cxx_compiler:
  - gxx     # [linux]
  - clangxx # [osx]
  - vs2022  # [win]
c_stdlib:
  - sysroot                  # [linux]
  - macosx_deployment_target # [osx]
  - vs                       # [win]
target_platform:  # [win]
  - win-64        # [win]
