package:
    name: nemaktis 
    version: "1.4.2"

source:
    - path: ../BeamPropagationSolver
      folder: bpm
    - path: ../RayTracingSolver
      folder: rtm
    - path: ../HighLevelPythonInterface
      folder: nemaktis
    - git_url: https://github.com/IJSComplexMatter/dtmm.git
      folder: dtmm

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }} # [not win]
        - {{ compiler('win_cxx') }} # [win]
        - vs2015_runtime # [win]
    host:
        - pkgconfig
        - muparser
        - pyfftw
        - fftw
        - boost 1.67.*
        - openmp
        - vtk 9.*
        - eigen
        - tbb-devel
        - swig
        - numpy-devel
        - numpy 1.18.*
        - numba
        - scipy 1.4.*
        - matplotlib
        - setuptools
        - python
    run:
        - muparser
        - pyfftw
        - fftw
        - libboost 1.67.*
        - openmp
        - vtk 9.*
        - eigen
        - numpy 1.18.*
        - numba
        - scipy 1.4.*
        - matplotlib
        - python
        - ipython
        - traits
        - traitsui
        - vs2015_runtime # [win]
