package:
    name: nemaktis 
    version: "1.4.3"

source:
    - path: ../BeamPropagationSolver
      folder: bpm
    - path: ../RayTracingSolver
      folder: rtm
    - path: ../HighLevelPythonInterface
      folder: nemaktis
    - git_url: https://github.com/IJSComplexMatter/dtmm.git
      folder: dtmm

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }} # [not win]
        - {{ compiler('win_cxx') }} # [win]
        - vs2015_runtime # [win]
    host:
        - pkgconfig
        - muparser
        - pyfftw
        - fftw
        - boost 1.73.*
        - openmp
        - vtk 9.*
        - eigen
        - tbb-devel
        - swig
        - numpy >=1.20
        - numba
        - scipy
        - matplotlib
        - setuptools
        - python 3.8.*
    run:
        - muparser
        - pyfftw
        - fftw
        - libboost 1.73.*
        - openmp
        - vtk 9.*
        - eigen
        - {{ pin_compatible('numpy') }}
        - numba
        - scipy
        - matplotlib
        - python  3.8.*
        - ipython
        - traits
        - traitsui
        - vs2015_runtime # [win]
