package:
    name: nemaktis 
    version: "1.0.10"

source:
    - path: ../BeamPropagationSolver
      folder: bpm
    - path: ../RayTracingSolver
      folder: rtm
    - path: ../HighLevelPythonInterface
      folder: nemaktis
    - git_url: https://github.com/IJSComplexMatter/dtmm.git
      folder: dtmm

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }} # [not win]
        - {{ compiler('win_cxx') }} # [win]
        - vs2015_runtime # [win]
    host:
        - pkgconfig
        - muparser
        - pyfftw
        - fftw
        - boost 1.67
        - openmp
        - vtk
        - eigen
        - tbb-devel
        - swig
        - numpy-devel
        - setuptools
        - python
    run:
        - muparser
        - pyfftw
        - fftw
        - libboost
        - openmp
        - vtk
        - eigen
        - numpy
        - numba
        - scipy
        - matplotlib
        - python
        - ipython
        - traits
        - traitsui
        - vs2015_runtime # [win]
