schema_version: 1

package:
  name: nemaktis
  version: "1.4.10"

source:
  - path: ../BeamPropagationSolver
    target_directory: bpm
  - path: ../RayTracingSolver
    target_directory: rtm
  - path: ../HighLevelPythonInterface
    target_directory: nemaktis
  - git: https://github.com/IJSComplexMatter/dtmm.git
    target_directory: dtmm

build:
  script:
    - if: win
      then: |
        if not exist bpm\bin mkdir bpm\bin
        if not exist rtm\bin mkdir rtm\bin

        cd bpm
        python -m pip install . -vv --config-settings=cmake.define.CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%
        if %ERRORLEVEL% neq 0 exit 1

        cd ..\rtm\bin
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ..
        if %ERRORLEVEL% neq 0 exit 1
        ninja install
        if %ERRORLEVEL% neq 0 exit 1

        cd ..\..\dtmm
        pip install . -v
        if %ERRORLEVEL% neq 0 exit 1

        cd ..\nemaktis
        pip install . -v
        if %ERRORLEVEL% neq 0 exit 1

requirements:
  build:
    - cmake >= 3.15
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ compiler('clang-cl') if win }}
    - ${{ stdlib('c') }}
    - vc14_runtime
  host:
    - pkgconfig
    - muparser
    - pyfftw 0.12.*
    - fftw
    - boost 1.82.*
    - openmp
    - vtk 9.*
    - eigen 3.3.*
    - tbb-devel
    - swig
    - numpy 1.21.*
    - numba
    - scipy
    - matplotlib-base
    - pyqt
    - pip
    - scikit-build-core
    - setuptools
    - python 3.9.*
  run:
    - muparser
    - pyfftw 0.12.*
    - fftw
    - libboost 1.82.*
    - openmp
    - vtk 9.*
    - eigen 3.3.*
    - ${{ pin_compatible('numpy',lower_bound="1.20",upper_bound="1.22") }}
    - numba
    - scipy
    - matplotlib-base
    - pyqt
    - python 3.9.*
    - ipython
    - traits
    - traitsui
    - if: win
      then: vc14_runtime