schema_version: 1

package:
  name: nemaktis
  version: "1.4.10"

about:
  homepage: https://nemaktis.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE
  summary: An open-source platform for light propagation in birefringent media
  description: |
    Nemaktis is an open-source platform including tools for propagating and
    visualising optical field in complex birefringent media such as liquid
    crystal (LC) layers. It includes three backends implementing advanced
    numerical methods for light propagation, as well as an easy-to-use high
    level interface in python allowing to quickly setup a simulation and
    visualize optical micrographs of a LC structure as in a real microscope.
  repository: https://github.com/warthan07/nemaktis
  documentation: https://nemaktis.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - warthan07

source:
  - path: ..
  - git: https://github.com/warthan07/dtmm.git
    branch: v0.7.1
    target_directory: dtmm

build:
  script:
    - if: win
      then: |      
        python -m pip install . -vv --config-settings=cmake.define.CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%
        if %ERRORLEVEL% neq 0 exit 1

        cd dtmm
        python -m pip install . -vv
        if %ERRORLEVEL% neq 0 exit 1
    - if: linux
      then: |      
        echo $CMAKE_ARGS
        python -m pip install . -vv

        cd dtmm
        python -m pip install . -vv

requirements:
  build:
    - cmake >= 3.15
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: win
      then:
        - ${{ compiler('clang-cl') }}
        - vc14_runtime
  host:
    - pkgconfig
    - muparser
    - pyfftw
    - fftw
    - boost 1.85.*
    - vtk
    - eigen
    - swig
    - numpy
    - numba
    - scipy
    - matplotlib-base
    - pip
    - scikit-build-core
    - hatch
    - python 3.12.*
    - if: win
      then:
        - vc14_runtime
        - llvm-openmp
    - if: linux
      then:
        - libstdcxx
        - libgomp
  run:
    - muparser
    - pyfftw
    - fftw
    - libboost 1.85.*
    - vtk
    - eigen
    - ${{ pin_compatible('numpy',lower_bound="1.20") }}
    - numba
    - scipy
    - matplotlib-base
    - pyqt
    - python 3.12.*
    - ipython
    - traits
    - traitsui
    - if: win
      then:
        - vc14_runtime
        - llvm-openmp
    - if: linux
      then:
        - libstdcxx
        - libgomp
