name: Package

on: [workflow_dispatch]

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target-platform: linux-64
          - os: windows-latest
            target-platform: win-64
          - os: macos-26-intel
            target-platform: osx-64
          - os: macos-latest
            target-platform: osx-arm64
    steps:
    - uses: actions/checkout@v6
    - name: Setup rattler-build
      uses: prefix-dev/rattler-build-action@v0.2.36
      with:
        setup-only: true
    - name: Build and upload
      run: |
        rattler-build build --recipe conda_recipe/recipe.yaml
        rattler-build upload anaconda -o warthan07 output/${{ matrix.target-platform }}/*.conda
      env:
        ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}

